version: '3'
services:
  api:
    image: node
    container_name: apiecommerce
    build: .
    command: npm start
    ports:
      - '8080:3000'
    networks:
      - backend
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin123
    ports:
      - '5432:5432'
    networks:
      - backend
networks:
  backend:
    driver: bridge

